accounts/urls.py
from django.conf.urls import include
from django.urls.conf import path
from accounts.views import ProfileView, RegisterView

app_name='accounts'

urlpatterns = [
    path('',include("django.contrib.auth.urls")),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
]

baseportal/urls.py
from django.urls.conf import path
from baseportal.views import HomePageView, TrackView, AboutUsView, ShowJournalView, SearchJournal, ListVolumeView, \
    ShowVolumeView, RulesAuthorView, RulesReviewerView, EditorialTeamView, VideoView

app_name='baseportal'

urlpatterns = [
    path('', HomePageView.as_view(), name="homepage"),
    path('track', TrackView.as_view(), name="track"),
    path('aboutus/', AboutUsView.as_view(), name="aboutus"),
    path('showjournal/<slug:journalslug>/', ShowJournalView.as_view(), name="showjournal"),
    path('listvolume', ListVolumeView.as_view(), name="listvolume"),
    path('showvolume/<int:volumeid>', ShowVolumeView.as_view(), name="showvolume"),
    path('search', SearchJournal.as_view(), name='search'),
    path('rules/author', RulesAuthorView.as_view(), name='rulesauthor'),
    path('rules/reviewer', RulesReviewerView.as_view(), name='rulesreviewer'),
    path('editorial', EditorialTeamView.as_view(), name='editorialteam'),
    path('video', VideoView.as_view(), name='video'),
]

ejournal/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls.conf import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('accounts/password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('author/', include('paperauthor.urls')),
    path('reviewer/', include('paperreviewer.urls')),
    path('api/', include('annotator.urls')),
    path('', include('baseportal.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paperauthor/urls.py
from django.urls.conf import path
from paperauthor.views import AuthorPortalView, AddPaperView, ShowPaperView, \
    DownloadPaperView, AnnotateView, ResubmitPaperView, DownloadSuggestedCorrectionsView, \
    DownloadPerformedCorrectionsView, PaperFinalSubmissionView

app_name='paperauthor'

urlpatterns = [
    path('portal/', AuthorPortalView.as_view(), name='portal'),
    path('addpaper/', AddPaperView.as_view(), name='addpaper'),
    path('showpaper/<slug:paperslug>/',
        ShowPaperView.as_view(), name='showpaper'),
    path('resubmitpaper/<slug:paperslug>/',
        ResubmitPaperView.as_view(), name='resubmitpaper'),
    path('downloadpaper/<slug:paperslug>.pdf',
        DownloadPaperView.as_view(), name='downloadpaper'),
    path('annotate.html', AnnotateView.as_view(), name='annotate'),
    path('downloadsuggestedcorrections/<slug:paperslug>.pdf',
        DownloadSuggestedCorrectionsView.as_view(), name='downloadsuggestedcorrections'),
    path('downloadperformedcorrections/<slug:paperslug>.pdf',
        DownloadPerformedCorrectionsView.as_view(), name='downloadperformedcorrections'),
    path('finalsubmitpaper/<slug:paperslug>/',
        PaperFinalSubmissionView.as_view(), name='finalsubmitpaper')
]

paperreviewer/urls.py
from django.urls.conf import path
from paperreviewer.views import ReviewerPortalView, ShowPaperView, \
    DownloadPaperView, ReviewPaperView, ReviewRequestView, AnnotateView, DownloadSuggestedCorrectionsView, \
    DownloadPerformedCorrectionsView

app_name='paperreviewer'

urlpatterns = [
    path('portal/', ReviewerPortalView.as_view(), name='portal'),
    path('showpaper/<slug:paperslug>/',
        ShowPaperView.as_view(), name='showpaper'),
    path('annotate.html', AnnotateView.as_view(), name='annotate'),
    path('reviewrequest/<int:paperid>/',
        ReviewRequestView.as_view(), name='reviewrequest'),
    path('reviewpaper/<slug:paperslug>/', ReviewPaperView.as_view(),
         name='reviewpaper'),
    path('downloadpaper/<slug:paperslug>.pdf',
        DownloadPaperView.as_view(), name='downloadpaper'),
    path('downloadsuggestedcorrections/<slug:paperslug>.pdf',
        DownloadSuggestedCorrectionsView.as_view(), name='downloadsuggestedcorrections'),
    path('downloadperformedcorrections/<slug:paperslug>.pdf',
        DownloadPerformedCorrectionsView.as_view(), name='downloadperformedcorrections'),
]

baseportal/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.utils import timezone
from slugger.fields import AutoSlugField


# Create your models here.

class Volume(models.Model):
    title = models.CharField(max_length=50)
    published_date = models.DateField()
    def __str__(self):
        return self.title


class PublishedJournal(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    upload = models.FileField(validators=[FileExtensionValidator(["pdf"])])
    preview_image = models.ImageField()
    slug = AutoSlugField(populate_from="name", unique=True, editable=False)
    volume = models.ForeignKey(Volume, on_delete=models.SET_NULL, null=True)
    def published_date(self):
        if self.volume is None:
            return ""
        return self.volume.published_date

    def __str__(self):
        return self.name

baseportal/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from paperauthor.models import Paper
from baseportal.models import PublishedJournal, Volume
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class HomePageView(View):
    def get(self, request):
        journals = PublishedJournal.objects.all()
        authors = User.objects.filter(groups__name='author')
        return render(request, "baseportal/homepage.html", {"journals": journals, "authors": authors})


class ListVolumeView(View):
    def get(self, request):
        volumes = Volume.objects.all()
        return render(request, "baseportal/listvolumes.html", {"volumes": volumes})


class ShowVolumeView(View):
    def get(self, request, volumeid):
        volume = Volume.objects.get(id=volumeid)
        return render(request, "baseportal/showvolume.html", {"volume": volume})


class SearchJournal(View):
    def get(self, request):
        keyword = request.GET.get("q", '')
        results = PublishedJournal.objects.filter(name__icontains=keyword)
        return render(request, "baseportal/search.html", {"results": results, "keyword": keyword})


class ShowJournalView(View):
    def get(self, request, journalslug):
        journal = get_object_or_404(PublishedJournal, slug=journalslug)
        return render(request, "baseportal/showjournal.html", {"journal": journal})


class AboutUsView(View):
    def get(self, request):
        return render(request, "baseportal/aboutus.html")


class TrackView(View):
    def get(self, request):
        track_id = request.GET.get('id', '')
        context = {"track_id": track_id}
        if track_id == '':
            context["showtrack"] = False
        else:
            try:
                paper = Paper.objects.get(track_id=track_id)

            except (ValidationError, ObjectDoesNotExist) as e:
                context["showerror"] = True
                paper = None

            if paper is not None:
                context["showtrack"] = True
                context["paper"] = paper
                if paper.reviewer is None:
                    context["trackstatus"] = 0
                elif paper.is_reviewed() is False:
                    context["trackstatus"] = 1
                else:
                    context["trackstatus"] = 2
        return render(request, "baseportal/track.html", context)


class RulesAuthorView(View):
    def get(self, request):
        return render(request, "baseportal/rules_author.html")


class RulesReviewerView(View):
    def get(self, request):
        return render(request, "baseportal/rules_reviewer.html")

class EditorialTeamView(View):
    def get(self, request):
        return render(request, "baseportal/editorialteam.html")

class VideoView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "baseportal/video.html")

baseportal/templates/baseportal/LICENSE.html
{% extends  'base.html' %}
{% load static %}

    {% block title %} LICENSE | NMAM Institute of Technology Research Journal  {% endblock %}

      {% block content %}


      	{% endblock %}

baseportal/templates/baseportal/aboutus.html
  {% extends  'base.html' %}
{% load static %}
{% block styles %}
<!-- Our Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/indexStyle.css' %}">
  <link rel="stylesheet" href="{% static 'css/aboutusStyle.css' %}">
  <link rel="stylesheet" href="{% static 'css/footerStyle.css' %}">
{% endblock %}
      {% block title %} NMAM Institute of Technology Annual Research Journal | About Institute {% endblock %}

      	{% block content %}
        <div class="content-x">
            <div class="container">
                <div class="row">
                    <div class="col-sm-12">
                        <h1>About Us</h1>
                        <hr>
                    </div>
                </div>
                <div class="row">
                    <div class="col-sm-12">
                        <p>NMAM Institute of Technology was started in the year 1986, as a part of Nitte Education
                          Trust, Mangalore and celebrated its Silver Jubilee in 2011. The Institute is named in fond memory
                          of Nitte Mahalinga Adyanthaya, a distinguished engineer of the district. It is affiliated to the
                          Visvesvaraya Technological University, Belgaum, enjoying academic autonomy and is recognized
                          by the All India Council for Technical Education, New Delhi. It is accredited by the National
                          Board for Accreditation and is certified to the ISO 9001 – 2008 standards for quality education
                          by KEMA, Netherlands. The Institute has been recognized as Lead Institute under TEQIP- I Project
                          of World Bank</p>
                    </div>
                </div>
                <hr>
                <div class="row">
                    <div class="col-sm-4">
                        <img src="{% static 'images/bg.jpeg' %}" class="dev-pic-x"/>
                    </div>
                    <div class="col-sm-8">
                        <p> The Institute offers B.E, M.Tech and Ph.D pragrammes in various Engineering and Technology
                        disciplines. The graduate programs comprise of 7 branches of Engineering – Electronics &
                        Communication Engineering, Computer Science & Engineeing, Civil Engineering, Electrical &
                        Electronics Engineering, Information Science & Engineering, Bio-Technology and Mechanical
                        Engineering. The Institute’s postgraduate programs include, Master of Technology in 13
                        disciplines, Master of Computer Applications and Master of Business Administration. The
                        Visvesvaraya Technological University has opened a postgraduate extension centre at NMAMIT,
                        offering M.Tech in Micro-electronics & Control Systems. Besides these, students also pursue
                        their M.Sc(Eng.) and Doctoral Programs at the Institute. The Institute got academic autonomy
                        in the year 2007, bringing in the much needed flexibility to innovate in terms of curriculum,
                        education delivery and evaluation. Institute entered into collaboration with Penn State University,
                        Harrisburg, USA and started offering 2+2 twinning program in Engineering since 2011.</p>
                    </div>
                </div>
                <hr>
            </div>
        </div>

    <!-- END - CONTENT -->
	{% endblock %}

baseportal/templates/baseportal/editorialteam.html
{% extends  'base.html' %}
{% load static %}
{% block styles %}
<!-- Our Custom CSS -->
<link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
<link rel="stylesheet" href="{% static 'css/indexStyle.css' %}">
<link rel="stylesheet" href="{% static 'css/aboutusStyle.css' %}">
<link rel="stylesheet" href="{% static 'css/footerStyle.css' %}">
<link rel="stylesheet" href="{% static 'css/editorialteamStyle.css' %}">
{% endblock %}
{% block title %} NMAM Institute of Technology Annual Research Journal | Editorial {% endblock %}

{% block content %}
<!-- START - CONTENT -->
<div class="content-x">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Members of Editorial Team</h1>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-4">
                <img src="{% static 'images/principal.jpg' %}" class="dev-pic-x"/>
            </div>
            <div class="col-sm-8">
                <h4>EDITOR-IN-CHEIF</h4>
                <p>Dr. Nirajnjan N. Chiplunkar</p>
                <p>NMAM Institute of Technology, Nitte</p>
            </div>
        </div>
        <hr class="col-sm-12">
        <div class="row">
            <div class="col-sm-8">
                <h4>EDITOR</h4>
                <p>Dr. Sudesh Bekal Dean (R&D)</p>
                <p>NMAM Institute of Technology, Nitte</p>

            </div>
            <div class="col-sm-4">
                <img src="{% static 'images/dean.jpg' %}" class="dev-pic-x"/>
            </div>
        </div>
        <hr class="col-sm-12">
        <div class="row">
            <div class="col-sm-12">
                <h4>EDITORIAL BOARD</h4>
                <h5>Dr. S. Y. Kulkarni </h5>
                <p>Reva University, Bangalore </p>
                <h5>Dr. N. S. Sriram </h5>
                <p>Vidya Vikas College of Engineering, Mysore </p>
                <h5>Dr. C. Vaman Rao </h5>
                <p>NMAM Institute of Technology, Nitte </p>
                <h5>Dr. Ashok Babu T. P. </h5>
                <p>National Institute of Technology Karnataka, Suratkal</p>
                <h5>Dr. Jaganath Nayak </h5>
                <p>National Institute of Technology Karnataka, Suratkal </p>
                <h5>Dr. Shridhara S.</h5>
                <p>Indian Institute of Technology Bombay, Mumbai</p>
                <h5>Dr. K. V. V. Murthy </h5>
                <p>Indian Institute of Technology, Gandhinagar </p>
                <h5>Dr. Navakanth Bhat </h5>
                <p>Indian Institute of Science & Communication, Bangalore </p>
                <h5>Dr. Gopalakrishna Kini </h5>
                <p>Manipal Institute of Technology, Manipal </p>
            </div>
        </div>
        <hr class="col-sm-12">
        <div class="row">
            <div class="col-sm-12">
                <h4>EDITORIAL ASSISTANTS </h4>
                <h5>Dr. Bharath B. R., NMAMIT, Nitte.</h5>
                <h5>Mr. Raghunandan K. R., NMAMIT, Nitte</h5>
            </div>
        </div>
    </div>
</div>

<!-- END - CONTENT -->
{% endblock %}

baseportal/templates/baseportal/homepage.html
{% extends  'base.html' %}
{% load static %}

            {% block title %}NMAMIT Annual Research Journal  {% endblock %}



  {% block styles %}
  <!-- Our Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/card.css' %}">
  <link rel="stylesheet" href="{% static 'css/w3.css' %}">
  <link rel="stylesheet" href="{% static 'css/sliderStyle.css' %}">
  <link rel="stylesheet" href="{% static 'css/slideshowStyle.css' %}">
  {% endblock %}
  {% block content %}
  <!-- START - CONTENT -->
  <div class="content-x">
      <div class="container">
          <div class="row">
            <div class="col-sm-12">
                <div class="w3-content w3-display-container">
                    <img class="mySlides fade" src="{% static 'images/1.jpg' %}" style="height: 500px;width:100%">
                    <img class="mySlides fade" src="{% static 'images/2.jpg' %}" style="height: 500px;width:100%">
                    <img class="mySlides fade" src="{% static 'images/3.jpg' %}" style="height: 500px;width:100%">
                    <img class="mySlides fade" src="{% static 'images/4.jpg' %}" style="height: 500px;width:100%">

                    <button class="w3-button w3-black w3-display-left" onclick="plusDivs(-1)">&#10094;</button>
                    <button class="w3-button w3-black w3-display-right" onclick="plusDivs(1)">&#10095;</button>
                  </div>
            </div>
          </div>

          <div class="featureBox-x row">
              <a href="{% url 'paperauthor:addpaper' %}">
              <div class="col-lg-3 well-x col-lg-push-1">
                  <img src="{% static 'images/contract-big.png' %}" class="high-menu-x"/>
                    <h1>Submit Your Paper</h1>
              </div>
              </a>
              <a href="{% url 'paperreviewer:portal' %}">
              <div class="col-lg-3 well-x col-lg-push-1">
                  <img src="{% static 'images/review-big.png' %}" class="high-menu-x"/>
                  <h1>Review Others Paper</h1>
              </div>
              </a>
              <a href="{% url 'baseportal:track' %}">
              <div class="col-lg-3 well-x col-lg-push-1">
                  <img src="{% static 'images/route-big.png' %}" class="high-menu-x"/>
                  <h1>Track your Paper Now</h1>
              </div>
              </a>
          </div>

            <!-- END - SLIDESHOW -->
            <div class="row">
                <div class="col-md-8">
                    <h1><u>Previous Journals</u></h1>
                    <div class="contain-y">
                        <div class="row-y">
                          <div class="row__inner">
                        {% for el in journals %}
                            <div class="tile">
                                <a href="{% url 'baseportal:showjournal' journalslug=el.slug %}">
                                  <div class="tile__media card">
                                    <div>
                                      <img src="{{el.preview_image.url}}" alt="{{el.preview_image.url}}" class="verticalSlidersImg">
                                    </div>
                                    <div>{{el.name}}</div>
                                    <div>{{el.published_date}}</div>
                                  </div>
                                </a>
                            </div>
                            {% endfor %}
                          </div>
                        </div>
                      </div>
                </div>
                <div class="counter-x col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading-x panel-heading counter-text" >TOTAL</div>
                        <div class="panel-body">
                            <p class="counter-text" >Authors : {{authors.count}}</p>
                            <p class="counter-text">Journals : {{journals.count}}</p>
                        </div>
                    </div>
                </div>
                <div class="counter-x col-md-4">
                    <div class="panel panel-default">
                        <div class="panel-heading-x panel-heading counter-text" >Archives</div>
                        <div class="panel-body">
                            <a href="{% url 'baseportal:listvolume' %}"> Click here for Archives  </a>
                        </div>
                    </div>
                </div>
            </div>
</div>
</div>

         <script type="text/javascript" src="{% static 'js/slideshow.js' %}"></script>
         <script>
             setInterval(function(){ plusDivs(1); }, 3000);
         </script>



	{% endblock %}

baseportal/templates/baseportal/listvolumes.html
{% extends  'base.html' %}
{% load static %}
{% block styles %}

  <link rel="stylesheet" href={% static 'css/treeView.css' %}>
{% endblock %}
{% block title %}Volumes | NMAMIT Annual Research Journal  {% endblock %}

	{% block content %}

  <!-- START - CONTENT -->
  <div class="content-x" style="height: 50%;">
      <div class="container">
          <div class="row">

              <div class="col-sm-7">
                  <h1><u>NMAM Annual Research Volumes</u></h1>
                  <hr>
                  <div class="col-sm-7">
                      <div class="tree">
                        {% for volume in volumes %}
                          <ul>
                              <li>
                                  <span><i class="icon-calendar">{{volume}}</i><!-- <a href="{% url 'baseportal:showvolume' volumeid=volume.id %}"> </a>--></span>
                                  {% for journal in volume.publishedjournal_set.all %}



                                  <ul>
                                      <li>
                                          <span class="badge badge-warning"><i class="icon-minus-sign"></i> {{journal}}</span>
                                            <a href="{% url 'baseportal:showjournal' journalslug=journal.slug %}" class="tree-download-x"><h5>View</h5></a>
                                      </li>

                                  </ul>

                                  {% endfor %}

                              </li>
                          </ul>
                            {% endfor %}
                      </div>
                  </div>
              </div>

              <div class="col-sm-5">
                  <img src="{% static 'images/ff.jpg' %}" class="showJImage">
              </div>

          </div>
      </div>
  </div>
  <script src="{% static 'js/jquery.min.js' %}"></script>
    <script type="text/javascript" src={% static 'js/treeView.js' %}></script>
{% endblock %}

baseportal/templates/baseportal/rules_reviewer.html
{% extends  'base.html' %}
{% load static %}
{% block styles %}
<!-- Our Custom CSS -->
<link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
<link rel="stylesheet" href="{% static 'css/indexStyle.css' %}">
<link rel="stylesheet" href="{% static 'css/aboutusStyle.css' %}">
<link rel="stylesheet" href="{% static 'css/footerStyle.css' %}">
{% endblock %}
{% block title %} Rules to reviewer | NMAM Institute of Technology Research Journal  {% endblock %}

{% block content %}
<div class="content-x">
  <div class="container">
    <div class="row">
      <div class="col-sm-12">
        <h1><u>Guidlines for Reviewer</u></h1>
        <hr>
            <h2>  How to conduct a review </h2>
            <h4> Before you accept or decline an invitation to review, consider the following questions: </h4>
            <ul>
              <li>Does the article match your area of expertise? Only accept if you feel you can provide a high quality review.</li>
              <li>Do you have a potential conflict of interest? Disclose this to the editor when you respond.</li>
              <li>Do you have time? Reviewing can be a lot of work – before you commit, make sure you can meet the deadline. </li>
              <li>Finally: Educate yourself on the peer review process through the free <a href="{% url 'baseportal:video' %}"> NMAMIT Annual Research Portal</a></li>
            </ul>
            <p>Respond to the invitation as soon as you can – delay in your decision slows down the review process, whether you agree to review or not. If you decline the invitation, provide suggestions for alternative reviewers.</p>

            <div>
              <h2>Before you start</h2>
              <p>If you accept, you must treat the materials you receive as confidential documents. This means you can’t share them with anyone without prior authorization from the editor. Since peer review is confidential, you also must not share information about the review with anyone without permission from the editors and authors.</p>
              <p>First read the article and then take a break from it, giving you time to think. Consider the article from your own perspective. When you sit down to write the review, make sure you know what the journal is looking for, and have a copy of any specific reviewing criteria you need to consider.</p>
              <br>
              <p>Authors may add research data, including data visualizations, to their submission to enable readers to interact and engage more closely with their research after publication. Please be aware that links to data might be present in the submission files. Manuscripts may also contain database identifiers or accession numbers (e.g. genes) in relation to our database linking program. These items should also receive your attention during the peer review process.</p>
            </div>
            <div>
              <h2>Your review report</h2>
              <p>Your review will help the editor decide whether or not to publish the article. Giving your overall opinion and general observations of the article is essential. Your comments should be courteous and constructive, and should not include any personal remarks or personal details including your name.</p>
              <p>Providing insight into any deficiencies is important. You should explain and support your judgement so that both editors and authors are able to fully understand the reasoning behind your comments. You should indicate whether your comments are your own opinion or are reflected by the data.</p>
            </div>
            <div>
              <h2>Checklist</h2>
              <ul>
                <li>Summarize the article in a short paragraph. This shows the editor you have read and understood the research.</li>
                <li>Give your main impressions of the article, including whether it is novel and interesting, whether it has a sufficient impact and adds to the knowledge base.</li>
                <li>Point out any journal-specific points – does it adhere to the NMAMIT Annual Research journal’s standards?</li>
                <li>Give specific comments and suggestions, including about layout and format, title, abstract, introduction, graphical abstracts and/or highlights, method, statistical errors, results, conclusion/discussion, language and references.</li>
                <li>If you suspect plagiarism, fraud or have other ethical concerns, raise your suspicions with the editor, providing as much detail as possible.</li>
                <li>Unconscious bias can lead us to make questionable decisions which impact negatively on the academic publishing process. Read further to find out more about this important subject and to view resources on how to identify and tackle bias.</li>
                <li>According to guidelines, reviewers must treat any manuscripts they are asked to review as confidential documents. Since peer review is confidential, they must not share the review or information about the review with anyone without the agreement of the editors and authors involved. This applies both during and after the publication process.</li>
                <li>Any suggestion that the author includes citations to reviewers’ (or their associates’) work must be for genuine scientific reasons and not with the intention of increasing reviewers’ citation counts or enhancing the visibility of reviewers’ work (or that of their associates).</li>
              </ul>
            </div>
            <div>
              <h2>Your recommendation</h2>
              <p>When you make a recommendation, it is worth considering the categories the editor most likely uses for classifying the article:</p>
                <ul>
                  <li>Reject (explain reason in report)</li>
                  <li>Accept without revision</li>
                  <li>Revise – either major or minor (explain the revision that is required, and indicate to the editor whether or not you would be happy to review the revised article)</li>
                </ul>
            </div>
            <div>
              <h2>The final decision</h2>
              <p>The editor ultimately decides whether to accept or reject the article. Elsevier plays no part in this decision. The editor will weigh all views and may call for a third opinion or ask the author for a revised paper before making a decision. The online editorial system provides reviewers with a notification of the final decision, if the journal has opted in to this function. If this is not applicable for your journal, you can contact the editor to find out whether the article was accepted or rejected.</p>
            </div>
        </div>
    </div>
  </div>
</div>

<!-- END - CONTENT -->
{% endblock %}

baseportal/templates/baseportal/search.html
{% extends  'base.html' %}
{% load static %}
{% block title %} Search results for {{keyword}} | NMAM Institute of Technology Research Journal  {% endblock %}
	{% block content %}
  <div class="content-x">
      <div class="container">
          <div class="row">
              <div class="col-sm-12">
                  <h1>Search Results "<i><u>{{keyword}}</u></i>"</h1>
                  <p>Total Results: <i>{{results.count}}</i></p>
                  <hr>
              </div>
          </div>
          <div class="row">
              {% if results %}
                {% for el in results %}
                <div class="col-sm-3">
                    <a href="{% url 'baseportal:showjournal' journalslug=el.slug %}">
                        <div class="card">
                          <img src="{{el.preview_image.url}}" alt="book img" class="verticalSlidersImg">
                          <h2>{{el.name}}</h2>
                        </div>
                    </a>
                </div>
                {% endfor %}
              {% else %}
              <div class="row">
                  <div class="col-sm-12 text-center">
                      <img src="{% static 'images/brokenRobot.png' %}" class="errorimg">
                      <h1>No Results Found! "{{keyword}}"</h1>
                      <h3>Try Again!</h3>
                  </div>
              </div>
              {% endif %}

        </div>
    </div>              {% endblock %}

baseportal/templates/baseportal/showvolume.html
<a href ="{% url 'baseportal:showvolume' volumeid=volume.id %}">{{volume}}</a>
Date:{{volume.published_date}}
{% for journal in volume.publishedjournal_set.all %}
    <a href="{% url 'baseportal:showjournal' journalslug=journal.slug %}">{{journal}}</a>
{% endfor %}