accounts/urls.py
from django.conf.urls import include
from django.urls.conf import path
from accounts.views import ProfileView, RegisterView

app_name='accounts'

urlpatterns = [
    path('',include("django.contrib.auth.urls")),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
]

ejournal/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls.conf import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('accounts/password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('author/', include('paperauthor.urls')),
    path('reviewer/', include('paperreviewer.urls')),
    path('api/', include('annotator.urls')),
    path('', include('baseportal.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paperreviewer/urls.py
from django.urls.conf import path
from paperreviewer.views import ReviewerPortalView, ShowPaperView, \
    DownloadPaperView, ReviewPaperView, ReviewRequestView, AnnotateView, DownloadSuggestedCorrectionsView, \
    DownloadPerformedCorrectionsView

app_name='paperreviewer'

urlpatterns = [
    path('portal/', ReviewerPortalView.as_view(), name='portal'),
    path('showpaper/<slug:paperslug>/',
        ShowPaperView.as_view(), name='showpaper'),
    path('annotate.html', AnnotateView.as_view(), name='annotate'),
    path('reviewrequest/<int:paperid>/',
        ReviewRequestView.as_view(), name='reviewrequest'),
    path('reviewpaper/<slug:paperslug>/', ReviewPaperView.as_view(),
         name='reviewpaper'),
    path('downloadpaper/<slug:paperslug>.pdf',
        DownloadPaperView.as_view(), name='downloadpaper'),
    path('downloadsuggestedcorrections/<slug:paperslug>.pdf',
        DownloadSuggestedCorrectionsView.as_view(), name='downloadsuggestedcorrections'),
    path('downloadperformedcorrections/<slug:paperslug>.pdf',
        DownloadPerformedCorrectionsView.as_view(), name='downloadperformedcorrections'),
]

paperreviewer/models.py
from django.db import models
from paperauthor.models import Paper
from django.contrib.auth.models import User


# Create your models here.
class PaperReviewRequest(models.Model):
    ACCEPTED = "ACC"
    REJECTED = "REJ"
    REVIEW_REQUEST_STATUS_CHOICES = (
        (ACCEPTED, "Accept"),
        (REJECTED, "Reject"),
    )
    status = models.CharField(
        max_length=3,
        choices=REVIEW_REQUEST_STATUS_CHOICES,
        blank=True,
        null=True,
        default=None,
    )
    reviewer = models.ForeignKey(User, on_delete=models.CASCADE, limit_choices_to={'groups__name': "reviewer"})
    paper = models.ForeignKey(Paper, on_delete=models.CASCADE, limit_choices_to={'reviewer': None})
    def __str__(self):
        return self.paper.title


class PaperReview(models.Model):
    ACCEPTED = "ACC"
    ACCEPTED_WITH_MINOR_CORRECTION = "AMI"
    ACCEPTED_WITH_MAJOR_CORRECTION = "AMA"
    REJECTED = "REJ"
    REVIEW_STATUS_CHOICES = (
        (ACCEPTED, "Accepted"),
        (ACCEPTED_WITH_MINOR_CORRECTION, "Accepted with minor correction"),
        (ACCEPTED_WITH_MAJOR_CORRECTION, "Accepted with major correction"),
        (REJECTED, "Rejected"),
    )
    paper = models.OneToOneField(Paper, on_delete=models.CASCADE)
    review_status = models.CharField(
        max_length=3,
        choices=REVIEW_STATUS_CHOICES,
        null=True,
        default=None,
    )
    comments_to_author = models.TextField(blank=True, null=True, default=None)
    comments_to_editor = models.TextField(blank=True, null=True, default=None)
    final_comments_to_author = models.TextField(blank=True, null=True, default=None)

    def review_complete(self):
        return self.paper.review_complete

    review_complete.boolean = True

    def __str__(self):
        return self.paper.title

paperreviewer/forms.py
from django.forms.models import ModelForm
from paperreviewer.models import PaperReview, PaperReviewRequest


class ReviewPaperForm(ModelForm):
    class Meta:
        model=PaperReview
        fields=("review_status", "comments_to_author", "comments_to_editor")

class ReviewRequestForm(ModelForm):
    def __init__(self, *args, **kwargs):
        super(ReviewRequestForm, self).__init__(*args,**kwargs)
        self.fields['status'].empty_label = None

    class Meta:
        model=PaperReviewRequest
        fields=('status',)

paperreviewer/views.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.shortcuts import render, redirect, get_object_or_404, Http404
from django.contrib.auth.mixins import UserPassesTestMixin, LoginRequiredMixin
from django.template.loader import render_to_string
from django.views.generic.base import View
from paperauthor.models import Paper
from paperreviewer.models import PaperReviewRequest
from django.core.exceptions import PermissionDenied
from sendfile import sendfile
from paperreviewer.forms import ReviewPaperForm, ReviewRequestForm
from django.urls import resolve, reverse


def send_review_request_accept_email(request, paper, reviewrequest):
    subject = "Review Request accepted"
    visiturl = request.build_absolute_uri(reverse("admin:paperreviewer_paperreviewrequest_changelist"))
    message = render_to_string("email/review_request_accept.txt", {"paper": paper, "visiturl": visiturl})
    editor_email = User.objects.get(is_superuser=True).email
    send_mail(subject, message, settings.ADMIN_EMAIL, [editor_email])


def send_review_request_reject_email(request, paper, reviewrequest):
    subject = "Review Request rejected"
    visiturl = request.build_absolute_uri(reverse("admin:paperreviewer_paperreviewrequest_changelist"))
    message = render_to_string("email/review_request_reject.txt", {"paper": paper, "visiturl": visiturl})
    editor_email = User.objects.get(is_superuser=True).email
    send_mail(subject, message, settings.ADMIN_EMAIL, [editor_email])


def send_reviewer_completed_review_email(request, paper, paperreview):
    subject = "Reviewer Completed review"
    visiturl = request.build_absolute_uri(reverse("admin:paperreviewer_paperreview_change",args=[paperreview.id]))
    message = render_to_string("email/reviewer_completed_review.txt",
                               {"paper": paper, "paperreview": paperreview, "visiturl": visiturl})
    editor_email = User.objects.get(is_superuser=True).email
    send_mail(subject, message, settings.ADMIN_EMAIL, [editor_email])


class IsReviewerMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        return user.groups.filter(name='reviewer').exists()


# Create your views here.
class ReviewerPortalView(IsReviewerMixin, LoginRequiredMixin, View):
    def get(self, request):
        papers = Paper.objects.filter(reviewer=request.user)
        reviewrequests = PaperReviewRequest.objects.filter(reviewer=request.user)
        context = {
            "papers": papers,
            "reviewrequests": reviewrequests,
        }
        return render(request, "paperreviewer/portal.html", context)


class ReviewRequestView(IsReviewerMixin, LoginRequiredMixin, View):
    def get(self, request, paperid):
        reviewrequest = get_object_or_404(PaperReviewRequest, id=paperid)
        if reviewrequest.reviewer != request.user:
            raise PermissionDenied
        if reviewrequest.status is not None:
            raise Http404
        paper = reviewrequest.paper
        form = ReviewRequestForm()
        context = {
            "paper": paper,
            "reviewrequest": reviewrequest,
            "form": form,
        }
        return render(request, "paperreviewer/reviewrequest.html", context)

    def post(self, request, paperid):
        reviewrequest = get_object_or_404(PaperReviewRequest, id=paperid)
        if reviewrequest.reviewer != request.user:
            raise PermissionDenied
        if reviewrequest.status is not None:
            raise Http404
        paper = reviewrequest.paper
        form = ReviewRequestForm(request.POST)
        if form.is_valid():
            status = form.cleaned_data.get("status")
            if status == PaperReviewRequest.ACCEPTED:
                PaperReviewRequest.objects.filter(paper=paper).update(status=PaperReviewRequest.REJECTED)
                paper.reviewer = request.user
                paper.save()
                send_review_request_accept_email(request, paper, reviewrequest)
            else:
                send_review_request_reject_email(request, paper, reviewrequest)
            reviewrequest.status = status
            reviewrequest.save()
            return redirect('paperreviewer:portal')
        context = {
            "paper": paper,
            "reviewrequest": reviewrequest,
            "form": form,
        }
        return render(request, "paperreviewer/reviewrequest.html", context)


class ShowPaperView(IsReviewerMixin, LoginRequiredMixin, View):
    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.reviewer != request.user:
            raise PermissionDenied
        return render(request, "paperreviewer/showpaper.html", {"paper": paper})


class ReviewPaperView(IsReviewerMixin, LoginRequiredMixin, View):
    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.reviewer != request.user:
            raise PermissionDenied
        if paper.is_reviewed():
            raise Http404
        form = ReviewPaperForm()
        return render(request, "paperreviewer/reviewpaper.html",
                      {"paper": paper, "form": form})

    def post(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.reviewer != request.user:
            raise PermissionDenied
        if paper.is_reviewed():
            raise Http404
        form = ReviewPaperForm(request.POST)
        if form.is_valid():
            review = form.save(commit=False)
            review.paper = paper
            review.save()
            send_reviewer_completed_review_email(request, paper, review)
            return redirect("paperreviewer:showpaper", paperslug=paper.slug)
        return render(request, "paperreviewer/reviewpaper.html",
                      {"paper": paper, "form": form})


class DownloadPaperView(IsReviewerMixin, LoginRequiredMixin, View):
    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.reviewer != request.user:
            raise PermissionDenied
        return sendfile(request, paper.upload.path, attachment=True)


class DownloadSuggestedCorrectionsView(IsReviewerMixin, LoginRequiredMixin, View):
    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.reviewer != request.user:
            raise PermissionDenied
        return sendfile(request, paper.paperresubmission.suggested_corrections.path, attachment=True)


class DownloadPerformedCorrectionsView(IsReviewerMixin, LoginRequiredMixin, View):
    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.reviewer != request.user:
            raise PermissionDenied
        return sendfile(request, paper.paperresubmission.performed_corrections.path, attachment=True)


class AnnotateView(IsReviewerMixin, LoginRequiredMixin, View):
    def get(self, request):
        uri = request.GET.get('file', '')
        a = resolve(uri)
        paperslug = a.kwargs["paperslug"]
        paper = get_object_or_404(Paper, slug=paperslug)
        return render(request, "annotate/viewer.html", {"paper": paper})

paperreviewer/templates/paperreviewer/portal.html
{% extends 'base.html' %}
{% load static %}
{%block styles %}
<link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
<link rel="stylesheet" href="{% static 'css/indexStyle.css' %}">
<link rel="stylesheet" href="{% static 'css/portalReviewerStyle.css' %}">
<link rel="stylesheet" href="{% static 'css/footerStyle.css' %}">
{% endblock %}
{% block title %}Review the Manuscript | NMAMIT Annual Research Journal  {% endblock %}
{% block content %}


<!-- START - CONTENT -->
<div class="content-x">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>Username is : <b><i>{{user}}</i></b><br> You can review the manuscipts from this web portal</h3>
                <hr>
            </div>

            <div class="col-sm-12">
                <h1><b>Under Review</b></h1>
                <table class="blue-grey lighten-4 table table-striped">
                    <thead>

                        <tr>
                            <th>Sl.</th>
                            <th>Paper Title</th>
                            <th>Author</th>
                            <th width="30">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                      	{% for el in papers %}
                            {% if not el.paperreview %}
                            <tr>
                                <td>{{el.id}}</td>
                                <td>{{el.title}}</td>
                                <td>{{el.review_status}}</td>
                                <td><a href="{% url 'paperreviewer:showpaper' paperslug=el.slug %}" class="btn btn-primary">Review</a></td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>

            <div class="col-sm-12">
                <h1><b>Review Requests</b></h1>
                <table class="blue-grey lighten-4 table table-striped">
                    <thead>
                        <tr>
                            <th>Sl.</th>
                            <th>Paper Title</th>
                            <th width="30">Action</th>
                        </tr>
                    </thead>
                    <tbody>
                      {% for el in reviewrequests %}
                      {% if el.status is None %}
                        <tr>
                            <td>{{el.id}}</td>
                            <td>{{el}}</td>
                            <td><a href="{% url 'paperreviewer:reviewrequest' paperid=el.id %}" class="btn btn-success">Accept/Reject</a></td>
                        </tr>
                        			{% endif %}
                        	{% endfor %}

                    </tbody>
                </table>
            </div>

            <div class="col-sm-12">
                <h1><b>Papers Reviewed</b></h1>
                <table class="blue-grey lighten-4 table table-striped">
                    <thead>
                        <tr>
                            <th>Sl.</th>
                            <th>Paper Title</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                      	{% for el in papers %}
                            {% if el.paperreview %}
                            <tr>
                                <td>{{el.id}}</td>
                                <td><a href="{% url 'paperreviewer:showpaper' paperslug=el.slug %}">{{el.title}}</a></td>
                                <td>{{el.review_status}}</td>
                            </tr>
                            {% endif %}
                        {% endfor %}
                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>

		<!--{% for el in reviewrequests %}
		<tr>
			<td class="button">
				{% if el.status is None %}
				<a class="fix" href="{% url 'paperreviewer:reviewrequest' paperid=el.id %}">
					{{el}}
				</a>
				{% else %}
					{{el}}
				{% endif %}
			</td>
			<td>
				{{el.get_status_display}}
			</td>
		</tr>
	{% endfor %}
	</tbody>
</table>
</div>-->
{% endblock %}

paperreviewer/templates/paperreviewer/reviewpaper.html
{% extends "base.html" %}
{% load crispy_forms_tags %}
{% load widget_tweaks %}
{% load static %}
{% block content %}
<div class="content-x">
		<a href="{% url 'paperreviewer:portal' %}"><img src="{% static 'images/left-blue.png' %}" class="back-button" alt="Reviewer Portal"></a>
		<div class="container">
			<form method="post">
				{% csrf_token %}
				<div class="row row-x">
						<div class="col-xs-8">
								<h1 class="counter-text margin-x h4 mb-4"><b>Review</b></h1>
						</div>
						<hr class="col-xs-11">
						<div class="col-xs-8 row-x">
								<div class="md-form">
										<i class="fa fa-user prefix grey-text"></i>
										{% render_field form.review_status class="comboBoxOne" %}{{ form.review_status.errors }}
								</div>
						</div>

						<div class="col-xs-8 row-x">
								<div class="md-form">
										{% render_field form.comments_to_author id="textareaBasic" class="form-control md-textarea" rows="3" %}{{ form.comments_to_author.errors }}
										<label for="textareaBasic">Comments to Author</label>
								</div>
						</div>

						<div class="col-xs-8 row-x">
								<div class="md-form">
										{% render_field form.comments_to_editor id="textareaBasic" class="form-control md-textarea" rows="3" required="true" %}{{ form.comments_to_editor.errors }}
										<label for="textareaBasic">Comments to Editor</label>
								</div>
						</div>

						<div class="col-xs-8 row-x">
								<div class="margin-x mt-4">
									<input class="btn btn-primary" type="submit" value="Submit Now" name=""/>
									<input class="btn btn-danger" type="reset" value="Reset" name=""/>

								</div>
						</div>

				</div>
		</form>
		</div>
</div>
{% endblock %}

paperreviewer/templates/paperreviewer/reviewrequest.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Review the Manuscript {{paper}}| NMAMIT Annual Research Journal  {% endblock %}
{%block styles %}
        <link rel="stylesheet" href="{% static 'css/reviewRequestStyle.css' %}"><!--CUSTOM STYLESHEET HRE-->
        <link rel="stylesheet" href="{% static 'css/passwordResetStyle.css' %}"><!--CUSTOM STYLESHEET HRE-->
        {% endblock %}
        {% block content %}
      <!-- START - CONTENT -->
                <div class="content-x text-center" style="min-height: 45%">

                    <div class="container">
                        <div class="row">
                            <div class="col-sm-12 text-center">
                                <h2>Do you want to Review this Paper?</h2>
                                <p>You can <u>Accept</u> or <u>Reject</u> this paper, We expect to Accept this paper from ur side.</p>
                                <hr>
                            </div>
                        </div>
                         <form class="text-center" method="POST">
                             <h3>Choose your option on {{paper}}</h3>
                            <div class="row row-x">
                                <div class="col-xs-12">
                                  {% csrf_token %}
                                  {{form}}
                                </div>
                            </div>
                            <div class="row row-x">
                               <div class="col-xs-12">
                                    <div class="margin-x mt-4">
                                        <button class="btn btn-primary" type="submit">Submit</button>
                                    </div>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            {% endblock %}

paperreviewer/templates/paperreviewer/showpaper.html
{% extends "base.html" %}
{% load static %}
{% block title %}Manuscript: {{paper}}| NMAMIT Annual Research Journal  {% endblock %}

{% block content %}
<!-- START - CONTENT -->
<div class="content-x" style="min-height:43%">
    <a href="{% url 'paperreviewer:portal' %}"><img src="{% static 'images/left-blue.png' %}" class="back-button" alt="Reviewer Portal"></a>
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Paper Name : {{paper}}</h1>
                <hr>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-12">
                <h4>Abstract : </h4>
            </div>
            <div class="col-sm-12">
                <p>{{paper.abstract}}</p>
            </div>
        </div>
        <div class="row">
            <div class="col-sm-2">
                <a  class="btn btn-danger" href="{% url 'paperreviewer:downloadpaper' paperslug=paper.slug %}">
              		Download PDF
              	</a>
            </div>

            <div class="col-sm-2">

              	{% if paper.is_reviewed %}
              		<h3>Paper already reviewed as {{paper.review_status}}</h3>
              	{% else %}
              	<a  class="btn btn-primary" href="{% url 'paperreviewer:annotate' %}?file={% url 'paperreviewer:downloadpaper' paperslug=paper.slug %}">Annotate</a>
              	  </div>
                    <div class="col-sm-2">
                  <a class="btn btn-info" href="{% url 'paperreviewer:reviewpaper' paperslug=paper.slug %}">
              		Review
              	</a>
              	{% endif %}
            </div>
            <div class="col-sm-2">
              {% if paper.is_resubmission %}
            		<a class="btn btn-info" href="{% url 'paperreviewer:downloadsuggestedcorrections' paperslug=paper.slug %}">
            		  Suggested Correction
            		</a>
              </div>
                <div class="col-sm-2">
            		<a class="btn btn-info" href="{% url 'paperreviewer:downloadperformedcorrections' paperslug=paper.slug %}">
            		  Performed Correction
            		</a>
            	{% endif %}
            </div>
        </div>
    </div>
</div>
{% endblock %}