accounts/urls.py
from django.conf.urls import include
from django.urls.conf import path
from accounts.views import ProfileView, RegisterView

app_name='accounts'

urlpatterns = [
    path('',include("django.contrib.auth.urls")),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
]

baseportal/urls.py
from django.urls.conf import path
from baseportal.views import HomePageView, TrackView, AboutUsView, ShowJournalView, SearchJournal, ListVolumeView, \
    ShowVolumeView, RulesAuthorView, RulesReviewerView, EditorialTeamView, VideoView

app_name='baseportal'

urlpatterns = [
    path('', HomePageView.as_view(), name="homepage"),
    path('track', TrackView.as_view(), name="track"),
    path('aboutus/', AboutUsView.as_view(), name="aboutus"),
    path('showjournal/<slug:journalslug>/', ShowJournalView.as_view(), name="showjournal"),
    path('listvolume', ListVolumeView.as_view(), name="listvolume"),
    path('showvolume/<int:volumeid>', ShowVolumeView.as_view(), name="showvolume"),
    path('search', SearchJournal.as_view(), name='search'),
    path('rules/author', RulesAuthorView.as_view(), name='rulesauthor'),
    path('rules/reviewer', RulesReviewerView.as_view(), name='rulesreviewer'),
    path('editorial', EditorialTeamView.as_view(), name='editorialteam'),
    path('video', VideoView.as_view(), name='video'),
]

ejournal/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls.conf import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('accounts/password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('author/', include('paperauthor.urls')),
    path('reviewer/', include('paperreviewer.urls')),
    path('api/', include('annotator.urls')),
    path('', include('baseportal.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

baseportal/models.py
from django.db import models
from django.core.validators import FileExtensionValidator
from django.utils import timezone
from slugger.fields import AutoSlugField


# Create your models here.

class Volume(models.Model):
    title = models.CharField(max_length=50)
    published_date = models.DateField()
    def __str__(self):
        return self.title


class PublishedJournal(models.Model):
    name = models.CharField(max_length=50)
    description = models.TextField(blank=True)
    upload = models.FileField(validators=[FileExtensionValidator(["pdf"])])
    preview_image = models.ImageField()
    slug = AutoSlugField(populate_from="name", unique=True, editable=False)
    volume = models.ForeignKey(Volume, on_delete=models.SET_NULL, null=True)
    def published_date(self):
        if self.volume is None:
            return ""
        return self.volume.published_date

    def __str__(self):
        return self.name

baseportal/views.py
from django.contrib.auth.models import User
from django.shortcuts import render, get_object_or_404
from django.views.generic.base import View
from django.core.exceptions import ValidationError, ObjectDoesNotExist
from paperauthor.models import Paper
from baseportal.models import PublishedJournal, Volume
from django.contrib.auth.mixins import LoginRequiredMixin


# Create your views here.

class HomePageView(View):
    def get(self, request):
        journals = PublishedJournal.objects.all()
        authors = User.objects.filter(groups__name='author')
        return render(request, "baseportal/homepage.html", {"journals": journals, "authors": authors})


class ListVolumeView(View):
    def get(self, request):
        volumes = Volume.objects.all()
        return render(request, "baseportal/listvolumes.html", {"volumes": volumes})


class ShowVolumeView(View):
    def get(self, request, volumeid):
        volume = Volume.objects.get(id=volumeid)
        return render(request, "baseportal/showvolume.html", {"volume": volume})


class SearchJournal(View):
    def get(self, request):
        keyword = request.GET.get("q", '')
        results = PublishedJournal.objects.filter(name__icontains=keyword)
        return render(request, "baseportal/search.html", {"results": results, "keyword": keyword})


class ShowJournalView(View):
    def get(self, request, journalslug):
        journal = get_object_or_404(PublishedJournal, slug=journalslug)
        return render(request, "baseportal/showjournal.html", {"journal": journal})


class AboutUsView(View):
    def get(self, request):
        return render(request, "baseportal/aboutus.html")


class TrackView(View):
    def get(self, request):
        track_id = request.GET.get('id', '')
        context = {"track_id": track_id}
        if track_id == '':
            context["showtrack"] = False
        else:
            try:
                paper = Paper.objects.get(track_id=track_id)

            except (ValidationError, ObjectDoesNotExist) as e:
                context["showerror"] = True
                paper = None

            if paper is not None:
                context["showtrack"] = True
                context["paper"] = paper
                if paper.reviewer is None:
                    context["trackstatus"] = 0
                elif paper.is_reviewed() is False:
                    context["trackstatus"] = 1
                else:
                    context["trackstatus"] = 2
        return render(request, "baseportal/track.html", context)


class RulesAuthorView(View):
    def get(self, request):
        return render(request, "baseportal/rules_author.html")


class RulesReviewerView(View):
    def get(self, request):
        return render(request, "baseportal/rules_reviewer.html")

class EditorialTeamView(View):
    def get(self, request):
        return render(request, "baseportal/editorialteam.html")

class VideoView(LoginRequiredMixin, View):
    def get(self, request):
        return render(request, "baseportal/video.html")

baseportal/templates/base.html
 <!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01 Transitional//EN" "http://www.w3.org/TR/html4/loose.dtd">
{% load static %}
<html>
	<head>
    <!-- Required meta tags -->
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1">
		<meta name="keywords" content="nmamit,journal,volume,nitte,annual,coding,editor,software,webdesign,html,resources" />
    <meta name="author" content="Mr. Harshit S K , Mr. Alfaf Shaikh , Mr. Amardhruva N Prabhu" />
    <meta name="robots" content="index, follow">
    <meta name="revisit-after" content="3 month">
		<meta property="og:locale" content="en_US" />
		<meta property="og:type" content="article" />
		<meta property="og:title" content="NMAMIT Annual Research Journal" />
		<meta property="og:description" content="Submit Review Publish Research Manuscript" />
		<link rel='dns-prefetch' href='//fonts.googleapis.com' />
		<link rel='dns-prefetch' href='//nmamit.nitte.edu.in' />
		<link rel='dns-prefetch' href='//nmamit.in' />
		<link rel="icon" type="image/png" href="{% static 'images/favicon.ico' %}"/>

		<title>{% block title %}{% endblock %}</title>

		    <!-- Bootstrap CSS CDN -->
        <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
        <!-- Our Custom CSS -->
        <link rel="stylesheet" href="{% static 'css/mdb.min.css' %}">
        <link rel="stylesheet" href="{% static 'css/indexStyle.css' %}">
        <link rel="stylesheet" href="{% static 'css/card.css' %}">
				<link rel="stylesheet" href="{% static 'css/footerStyle.css' %}">
				{% block styles %}
 				{% endblock %}
        <!-- END - IMPORT STYLESHEETS -->

        <!-- END - INITIAL INCLUDES -->


	</head>
	<body>

		<div class="wrapper">
				<!-- Sidebar Holder -->
				<nav id="sidebar" class="active">
						<!-- Close Sidebar Button -->
				<div id="dismiss">
						<img src="{% static 'images/switch-arrows.png' %}" class="side-nav-icon">
				</div>

						<div class="sidebar-header">
								<h3><a href="{% url 'baseportal:homepage' %}"><img src="{% static 'images/logo.png' %}" class="logo-x"></a></h3>
								<strong><a href="{% url 'baseportal:homepage' %}"><img src="{% static 'images/favicon.ico' %}" class="logo-min-x"></a></strong>
						</div>

						<ul class="list-unstyled components">
								<li class="active">
										<a href="{% url 'baseportal:homepage' %}">
												<img src="{% static 'images/nitteUniversityIcon.ico' %}" class="side-nav-icon">
												Home
										</a>
								</li>
								{% if user.is_authenticated %}
								<li>
										<a href="{% url 'accounts:profile' %}">
												<img src="{% static 'images/note.png' %}" class="side-nav-icon">
												Profile
										</a>
								</li>
								<li>
										<a href="{% url 'accounts:logout' %}">
												<img src="{% static 'images/login.png' %}" class="side-nav-icon">
												Logout
										</a>
								</li>
								{% else %}
								<li>
										<a href="{% url 'accounts:register' %}">
												<img src="{% static 'images/note.png' %}" class="side-nav-icon">
												Register
										</a>
								</li>
								<li>
										<a href="{% url 'accounts:login' %}">
												<img src="{% static 'images/login.png' %}" class="side-nav-icon">
												Login
										</a>
								</li>
								{%endif%}
								<li>
										<a href="{% url 'baseportal:track' %}">
												<img src="{% static 'images/route.png' %}" class="side-nav-icon">
												Track
										</a>
								</li>
								<li>
										<a href="{% url 'baseportal:aboutus' %}">
												<img src="{% static 'images/about-us.png' %}" class="side-nav-icon">
												About Us
										</a>
								</li>

								<li>
										<a href="{% url 'baseportal:editorialteam' %}">
												<img src="{% static 'images/meeting.png' %}" class="side-nav-icon">
												Editorial Team
										</a>
								</li>
								<li><a href="{% url 'baseportal:rulesauthor' %}" class="download">Guidelines for Author</a></li>
								<li><a href="{% url 'baseportal:rulesreviewer' %}" class="article">Guidelines for Reviewer</a></li>
								<li><a href="{% url 'baseportal:video' %}" class="download">Tutorials to use Web Portal</a></li>
						</ul>

						<ul class="list-unstyled CTAs">

						</ul>
				</nav>

				<!-- Page Content Holder -->
				<div id="content">
					 <nav class="navbar navbar-inverse">
								<div class="container-fluid">
										<div class="navbar-header">
												<p class="counter-text txt-white">NMAMIT Annual Research Journal</p>
										</div>
										<div class="navbar-right">
												<ul class="list-unstyled">
														<li class="dropdown pull-right">
																<a href="#" data-toggle="dropdown" class="dropdown-toggle">
																				<img src="{% static 'images/man.png' %}" class="profile-x navbar-right">
																</a>
																<ul class="dropdown-menu">
																	{% if user.is_authenticated %}
																		<li><a href="{% url 'accounts:profile' %}" class="profile-opt-x"><img src="{% static 'images/profile.png' %}" class="margin-right-x">Profile</a></li>
																		<!--<li><a href="#" class="profile-opt-x"><img src="{% static 'images/settings-cog.png' %}" class="margin-right-x">Settings</a></li>-->
																		<li class="divider"></li>
																		<li><a href="{% url 'accounts:logout' %}" class="profile-opt-x"><img src="{% static 'images/login2.png' %}" class="margin-right-x">Sign Out</a></li>
																		{% else %}
																		<li><a href="{% url 'accounts:register' %}" class="profile-opt-x"><img src="{% static 'images/profile.png' %}" class="margin-right-x">Register</a></li>
																		<li class="divider"></li>
																		<li><a href="{% url 'accounts:login' %}" class="profile-opt-x"><img src="{% static 'images/login2.png' %}" class="margin-right-x">Sign IN</a></li>
																		{% endif %}
																</ul>
														</li>
												</ul>
										</div>

										<form class="search-x navbar-form navbar-right" method='get' action="{% url 'baseportal:search' %}">
												<div class="md-form mt-0">
														<input class="form-control" type="text" placeholder="Search" aria-label="Search" name="q" required>
														<i class="fa fa-search text-white ml-3" aria-hidden="true">

																		<button type="submit" style="border: 0px solid #2d5ccl; background-color: #2d5ccl"><img src="{% static 'images/searchBlack.png' %}" class="side-nav-search"></button>
														</i>
												</div>
										</form>
								</div>
						</nav>

         	{% block content %}

				{% endblock %}


            <!-- START - FOOTER -->
            <div class="footer-distributed">
                <div class="footer-left">
				    <img src="{% static 'images/logo.png' %}" class="logo-x">
				        <p class="footer-links">
					       <a href="{% url 'baseportal:homepage' %}">Home</a>
					       |
					       <a href="{% url 'baseportal:track' %}">Track</a>
                |
					       <a href="{% url 'baseportal:aboutus' %}">About Us</a>
								 |
								 <a href="http://nmamit.nitte.edu.in/privacy.php">Privacy Policy</a>
								 |
								 <a href="http://nmamit.nitte.edu.in/legal.php">Legal</a>
				        </p>
				        <p class="footer-company-name">NMAM Institute Of Technology, Nitte &copy; 2015-18</p>
			     </div>
					 <div class="footer-center">
 					 <div>
 						<i class="fa fa-map-marker"><img src="{% static 'images/placeholder.png' %}" class="footer-icon"></i>
 						<p><span>Nitte, Udupi</span> Karnataka, India - 574110</p>
 					 </div>
 					 <div>
 						<i class="fa fa-phone"><img src="{% static 'images/phone-receiver.png' %}" class="footer-icon"></i>
 						<p>+91-8258-281263</p>
 					 </div>
 					 <div>
						 <i class="fa fa-envelope"><img src="{% static 'images/envelope.png' %}"></i>
 						<p><a href="mailto:nmamit.arj@gmail.com">nmamit.arj@gmail.com</a></p>
 					 </div>
 					</div>
 					<div class="footer-right">
 					 <p class="footer-company-about">
 						<span>About the University</span>
						NMAM Institute of Technology
						An Autonomous Institution Under VTU, Belagavi
						(A Unit of Nitte Education Trust)
						www.nitte.edu.in/nmamit
 					 </p>
 					 <div class="footer-icons">
 						<a href="https://www.facebook.com/NITTEedu"><i class="fa fa-facebook"><img src="{% static 'images/facebook-logo.png' %}"/></i></a>
 						<a href="https://twitter.com/aboutnitte"><i class="fa fa-twitter"><img src="{% static 'images/twitter.png' %}"/></i></a>
 						<a href="https://www.youtube.com/channel/UCNln_L2YkP-QCFLfIDumNZQ"><i class="fa fa-youtube"><img src="{% static 'images/linked-in.png' %}"/></i></a>
 					 </div>
 					</div>

 					 </div>
					 	<p style="text-align: center; color: white; background-color: black; font-size: 10px;"> Design and Developed by Mr. Amardhruva N Prabhu ; Mr. Alfaf A. Shaikh and Mr. Harshit S K with Co-ordinated by Prof. Raghunandan K R </p>
        </div>
        <!-- END - MAIN CONTENT BOX -->
				<!-- jQuery CDN -->
				 <script src="{% static 'js/jquery.min.js' %}"></script>
				 <!-- Bootstrap Js CDN -->
				 <script src="{% static 'js/bootstrap.min.js' %}"></script>
				 <script type="text/javascript" src="{% static 'js/mdb.min.js' %}"></script>
				 <script type="text/javascript">
							$(document).ready(function () {
									$('#sidebarCollapse,#dismiss, .overlay').on('click', function () {
											$('#sidebar').toggleClass('active');
									});
							});
				 </script>



	</body>
</html>