accounts/urls.py
from django.conf.urls import include
from django.urls.conf import path
from accounts.views import ProfileView, RegisterView

app_name='accounts'

urlpatterns = [
    path('',include("django.contrib.auth.urls")),
    path('profile/', ProfileView.as_view(), name='profile'),
    path('register/', RegisterView.as_view(), name='register'),
]

baseportal/urls.py
from django.urls.conf import path
from baseportal.views import HomePageView, TrackView, AboutUsView, ShowJournalView, SearchJournal, ListVolumeView, \
    ShowVolumeView, RulesAuthorView, RulesReviewerView, EditorialTeamView, VideoView

app_name='baseportal'

urlpatterns = [
    path('', HomePageView.as_view(), name="homepage"),
    path('track', TrackView.as_view(), name="track"),
    path('aboutus/', AboutUsView.as_view(), name="aboutus"),
    path('showjournal/<slug:journalslug>/', ShowJournalView.as_view(), name="showjournal"),
    path('listvolume', ListVolumeView.as_view(), name="listvolume"),
    path('showvolume/<int:volumeid>', ShowVolumeView.as_view(), name="showvolume"),
    path('search', SearchJournal.as_view(), name='search'),
    path('rules/author', RulesAuthorView.as_view(), name='rulesauthor'),
    path('rules/reviewer', RulesReviewerView.as_view(), name='rulesreviewer'),
    path('editorial', EditorialTeamView.as_view(), name='editorialteam'),
    path('video', VideoView.as_view(), name='video'),
]

ejournal/urls.py
from django.conf.urls import include
from django.contrib import admin
from django.urls.conf import path
from django.conf.urls.static import static
from django.conf import settings
from django.contrib.auth import views as auth_views


urlpatterns = [
    path('accounts/password_reset/done/', auth_views.password_reset_done, name='password_reset_done'),
    path('admin/', admin.site.urls),
    path('accounts/', include('accounts.urls')),
    path('author/', include('paperauthor.urls')),
    path('reviewer/', include('paperreviewer.urls')),
    path('api/', include('annotator.urls')),
    path('', include('baseportal.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

paperauthor/urls.py
from django.urls.conf import path
from paperauthor.views import AuthorPortalView, AddPaperView, ShowPaperView, \
    DownloadPaperView, AnnotateView, ResubmitPaperView, DownloadSuggestedCorrectionsView, \
    DownloadPerformedCorrectionsView, PaperFinalSubmissionView

app_name='paperauthor'

urlpatterns = [
    path('portal/', AuthorPortalView.as_view(), name='portal'),
    path('addpaper/', AddPaperView.as_view(), name='addpaper'),
    path('showpaper/<slug:paperslug>/',
        ShowPaperView.as_view(), name='showpaper'),
    path('resubmitpaper/<slug:paperslug>/',
        ResubmitPaperView.as_view(), name='resubmitpaper'),
    path('downloadpaper/<slug:paperslug>.pdf',
        DownloadPaperView.as_view(), name='downloadpaper'),
    path('annotate.html', AnnotateView.as_view(), name='annotate'),
    path('downloadsuggestedcorrections/<slug:paperslug>.pdf',
        DownloadSuggestedCorrectionsView.as_view(), name='downloadsuggestedcorrections'),
    path('downloadperformedcorrections/<slug:paperslug>.pdf',
        DownloadPerformedCorrectionsView.as_view(), name='downloadperformedcorrections'),
    path('finalsubmitpaper/<slug:paperslug>/',
        PaperFinalSubmissionView.as_view(), name='finalsubmitpaper')
]

paperauthor/models.py
import uuid
from django.db import models
from django.contrib.auth.models import User
from django.conf import settings
from django.core.files.storage import FileSystemStorage
from slugger.fields import AutoSlugField
from django.core.exceptions import ValidationError
from django.core.validators import FileExtensionValidator

private_storage = FileSystemStorage(location=settings.SENDFILE_ROOT)


# Create your models here.
class Category(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name
    class Meta:
        verbose_name_plural = "categories"

class Keyword(models.Model):
    name=models.CharField(max_length=50)
    def __str__(self):
        return self.name

class ReviewerEmail(models.Model):
    email=models.EmailField()
    def __str__(self):
        return self.email

class Paper(models.Model):
    author=models.ForeignKey(User, on_delete=models.CASCADE,
                             limit_choices_to={'groups__name': "author"})
    all_authors=models.TextField(blank=True, null=True)
    title=models.CharField(max_length=500)
    abstract=models.TextField(max_length=8000, blank=True)
    category=models.ForeignKey(Category, on_delete=models.CASCADE)
    keywords=models.ManyToManyField(Keyword, blank=True)
    upload=models.FileField(storage=private_storage,
                             validators=[FileExtensionValidator(["pdf"])])
    reviewer_emails=models.ManyToManyField(ReviewerEmail, blank=True)
    reviewer = models.ForeignKey(User, null=True, blank=True,
                                 default=None, on_delete=models.SET_NULL,
                                 limit_choices_to={'groups__name': "reviewer"},
                                 related_name="reviewpaper")
    slug=AutoSlugField(populate_from="title", unique=True)
    track_id = models.UUIDField(unique=True, default=uuid.uuid4)
    review_complete = models.BooleanField(default=False)
    submission_date = models.DateField(auto_now_add=True)

    RESUBMIT_ALLOW=["AMI", "AMA"]
    FINALSUBMISSION_ALLOW=["ACC"]
    def review_status(self):
        return self.paperreview.get_review_status_display()
    def is_reviewed(self):
        return hasattr(self, "paperreview")
    def is_resubmission(self):
        return hasattr(self, "paperresubmission")
    def has_resubmission(self):
        return self.resubmissions_set.exists()
    def has_finalsubmission(self):
        return hasattr(self,"paperfinalsubmission")
    def is_resubmittable(self):
        return (not self.has_resubmission()) and (self.paperreview.review_status in self.RESUBMIT_ALLOW) and (self.review_complete)
    def is_finalsubmittable(self):
        return (not self.has_resubmission()) and (self.paperreview.review_status in self.FINALSUBMISSION_ALLOW) and (self.review_complete) and not (self.has_finalsubmission())
    def __str__(self):
        return self.title

class PaperResubmission(models.Model):
    paper=models.OneToOneField(Paper, on_delete=models.CASCADE)
    original_paper=models.ForeignKey(Paper, on_delete=models.CASCADE, related_name='resubmissions_set')
    suggested_corrections=models.FileField(storage=private_storage,
                             validators=[FileExtensionValidator(["pdf"])])
    performed_corrections=models.FileField(storage=private_storage,
                             validators=[FileExtensionValidator(["pdf"])])

class PaperFinalSubmission(models.Model):
    paper=models.OneToOneField(Paper, on_delete=models.CASCADE)
    upload=models.FileField(validators=[FileExtensionValidator(["docx"])])
    def __str__(self):
        return self.paper.title
    

paperauthor/forms.py
from django.forms.models import ModelForm
from paperauthor.models import Paper, PaperResubmission, PaperFinalSubmission


class PaperForm(ModelForm):
    class Meta:
        model = Paper
        fields = ('title', 'all_authors', 'abstract', 'category', 'upload', 'keywords')

class PaperResubmissionForm(ModelForm):
    class Meta:
        model = Paper
        fields = ('title', 'all_authors', 'abstract', 'upload')
    def __init__(self, *args, **kwargs):
        super(PaperResubmissionForm, self).__init__(*args,**kwargs)
        self.fields["title"].disabled=True
        #self.fields["category"].disabled=True

class PaperFinalSubmissionForm(ModelForm):
    class Meta:
        model = PaperFinalSubmission
        fields = ('upload',)

class ResubmissionForm(ModelForm):
    class Meta:
        model = PaperResubmission
        fields = ('suggested_corrections','performed_corrections')

paperauthor/views.py
from django.conf import settings
from django.contrib.auth.models import User
from django.core.mail import send_mail
from django.forms import model_to_dict
from django.shortcuts import render, redirect, get_object_or_404
from django.template.loader import render_to_string
from django.views.generic.base import View
from paperauthor.forms import PaperForm, PaperResubmissionForm, ResubmissionForm, PaperFinalSubmissionForm
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from paperauthor.models import Paper
from django.core.exceptions import PermissionDenied
from sendfile import sendfile
from django.urls import resolve, reverse

from paperreviewer.models import PaperReview


class IsAuthorMixin(UserPassesTestMixin):
    def test_func(self):
        user = self.request.user
        return user.groups.filter(name='author').exists()


def send_add_paper_email(request, paper):
    subject = "Paper has been added"
    visiturl = request.build_absolute_uri(reverse("admin:paperauthor_paper_change", args=[paper.id]))
    message = render_to_string("email/addpaper.txt", {"paper": paper, "visiturl": visiturl})
    editor_email = User.objects.get(is_superuser=True).email
    send_mail(subject, message, settings.ADMIN_EMAIL, [editor_email])
    visiturl = request.build_absolute_uri(reverse("paperauthor:showpaper", args=[paper.slug]))
    message = render_to_string("email/addpaperauthor.txt", {"paper": paper, "visiturl": visiturl})
    send_mail(subject, message, settings.ADMIN_EMAIL, [paper.author.email])

def send_final_submission_email(request, finalsubmit):
    subject = "Final Submission of paper completed"
    paper = finalsubmit.paper
    visiturl = request.build_absolute_uri(reverse("admin:paperauthor_paperfinalsubmission_change", args=[finalsubmit.id]))
    editor_email = User.objects.get(is_superuser=True).email
    message = render_to_string("email/final_submit_complete_admin.txt", {"paper": paper, "visiturl": visiturl})
    send_mail(subject, message, settings.ADMIN_EMAIL, [editor_email])
    visiturl = request.build_absolute_uri(reverse("paperauthor:showpaper", args=[paper.slug]))
    message = render_to_string("email/final_submit_complete_author.txt", {"paper": paper, "visiturl": visiturl})
    send_mail(subject, message, settings.ADMIN_EMAIL, [paper.author.email])

# Create your views here.
class AuthorPortalView(IsAuthorMixin, LoginRequiredMixin, View):
    def get(self, request):
        papers = Paper.objects.filter(author=request.user)
        context = {
            "papers": papers
        }
        return render(request, "paperauthor/portal.html", context)


class AddPaperView(IsAuthorMixin, LoginRequiredMixin, View):
    def get(self, request):
        form = PaperForm()
        return render(request, "paperauthor/addpaper.html", {"form": form})

    def post(self, request):
        form = PaperForm(request.POST, request.FILES)
        if form.is_valid():
            paper = form.save(commit=False)
            paper.author = request.user
            paper.save()
            send_add_paper_email(request, paper)
            return redirect('paperauthor:portal')
        return render(request, "paperauthor/addpaper.html", {"form": form})


class ResubmitPaperView(IsAuthorMixin, LoginRequiredMixin, View):
    resubmit_allow = [PaperReview.ACCEPTED_WITH_MINOR_CORRECTION, PaperReview.ACCEPTED_WITH_MAJOR_CORRECTION]

    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if (paper.author != request.user) or not paper.is_resubmittable():
            raise PermissionDenied
        paperinitial = model_to_dict(paper, fields=('title', 'abstract', 'category','all_authors'))
        form = [
            PaperResubmissionForm(initial=paperinitial),
            ResubmissionForm()
        ]
        return render(request, "paperauthor/resubmit.html", {"form": form})

    def post(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if (paper.author != request.user) or not paper.is_resubmittable():
            raise PermissionDenied
        paperinitial = model_to_dict(paper, fields=('title', 'abstract', 'category'))
        form = [
            PaperResubmissionForm(request.POST, request.FILES, initial=paperinitial),
            ResubmissionForm(request.POST, request.FILES)
        ]
        if form[0].is_valid() and form[1].is_valid():
            newpaper = form[0].save(commit=False)
            newpaper.reviewer = paper.reviewer
            newpaper.author = paper.author
            newpaper.category = paper.category
            newpaper.save()
            resubmission = form[1].save(commit=False)
            resubmission.paper = newpaper
            resubmission.original_paper = paper
            resubmission.save()
            return redirect('paperauthor:portal')

        return render(request, "paperauthor/resubmit.html", {"form": form})


class ShowPaperView(IsAuthorMixin, LoginRequiredMixin, View):
    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.author != request.user:
            raise PermissionDenied
        return render(request, "paperauthor/showpaper.html", {"paper": paper})


class DownloadPaperView(IsAuthorMixin, LoginRequiredMixin, View):
    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.author != request.user:
            raise PermissionDenied
        return sendfile(request, paper.upload.path, attachment=True)


class DownloadSuggestedCorrectionsView(IsAuthorMixin, LoginRequiredMixin, View):
    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.author != request.user:
            raise PermissionDenied
        return sendfile(request, paper.paperresubmission.suggested_corrections.path, attachment=True)


class DownloadPerformedCorrectionsView(IsAuthorMixin, LoginRequiredMixin, View):
    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.author != request.user:
            raise PermissionDenied
        return sendfile(request, paper.paperresubmission.performed_corrections.path, attachment=True)

class PaperFinalSubmissionView(IsAuthorMixin, LoginRequiredMixin, View):
    def get(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.author != request.user or not paper.is_finalsubmittable():
            raise PermissionDenied
        form = PaperFinalSubmissionForm()
        return render(request, "paperauthor/finalsubmit.html",{"form":form, "paper":paper})
    
    def post(self, request, paperslug):
        paper = Paper.objects.get(slug=paperslug)
        if paper.author != request.user or not paper.is_finalsubmittable():
            raise PermissionDenied
        form = PaperFinalSubmissionForm(request.POST, request.FILES)
        if form.is_valid:
            finalsubmit = form.save(commit=False)
            finalsubmit.paper = paper
            finalsubmit.save()
            send_final_submission_email(request, finalsubmit)
            return render(request, "paperauthor/finalsubmitsuccess.html",{"paper":paper})
        return render(request, "paperauthor/finalsubmit.html",{"form":form, "paper":paper})
        


class AnnotateView(IsAuthorMixin, LoginRequiredMixin, View):
    def get(self, request):
        uri = request.GET.get('file', '')
        a = resolve(uri)
        paperslug = a.kwargs["paperslug"]
        paper = get_object_or_404(Paper, slug=paperslug)
        return render(request, "annotate/viewerreadonly.html", {"paper": paper})

paperauthor/templates/paperauthor/addpaper.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block styles %}
<link rel="stylesheet" href="{% static 'css/registerStyle.css' %}">
<link rel="stylesheet" href="{% static 'css/addPaperStyle.css' %}">
{% endblock %}
{% block title %} New Manuscript | NMAMIT Annual Research Journal  {% endblock %}
{% block content %}
<!-- START - SUBMIT FORM-->
<div class="content-x">
		<div class="container">
		<form method="post" enctype='multipart/form-data'>
								{% csrf_token %}
				<div class="row row-x">
						<div class="col-xs-8">
								<h1 class="counter-text margin-x h4 mb-4"><b>Fill in detials to add your Paper</b></h1>
						</div>
				<hr class="col-xs-11">
						<div class="col-xs-8 row-x">
								<div class="md-form">
										<i class="fa fa-user prefix grey-text"></i>
										{% render_field form.title id="materialFormRegisterNameEx" class="form-control" %}{{ form.title.errors }}
										<label for="materialFormRegisterNameEx">Title</label>
								</div>
						</div>

						<div class="col-xs-8 row-x">
								<div class="md-form">
										{% render_field form.abstract id="textareaBasic" class="form-control md-textarea" rows="3" %}{{ form.description.errors }}
										<label for="textareaBasic">Abstract</label>
								</div>
						</div>

						<div class="col-xs-8 row-x">
										<label>Category</label>
										{% render_field form.category class="comboBoxOne" %}{{ form.category.errors }}
						</div>

						<div class="col-xs-8 row-x">
								<div class="textarea-x md-form">
										<i class="fa fa-user prefix grey-text"></i>
										<p><b>Keywords (Hold control for multiple selection)</b></p>
										{% render_field form.keywords rows="5"  id="materialFormRegisterNameEx" class="sdd form-control" data-role="tagsinput" %}{{ form.keywords.errors }}
								</div>
						</div>

						<div class="col-xs-8 row-x">
								 <div class="md-form">
										<div class="file-field">
												<div class="btn btn-primary btn-sm float-left">
														<span class="file-text-x">Choose file</span>
														{% render_field form.upload class="file-text-x" type="file" accept="application/pdf" %}{{ form.upload.errors }}
												</div>
										</div>
								</div>
						</div>
						<div class="col-xs-8 row-x">
								<div class="md-form">
										{% render_field form.all_authors id="textareaBasic" class="form-control md-textarea" rows="3" %}{{ form.all_authors.errors }}
										<label for="textareaBasic">Other Author details (Full Name and Email Separated with Comma Eg: John Doe, john@example.com; Eva Joe, eva@example.com)</label>
								</div>
						</div>
						<div class="col-xs-8 row-x">
								<div class="margin-x mt-4">
								<input type="submit" class="btn btn-primary" value="SUBMIT Manuscript">
								<input type="reset" class="btn btn-danger" value="RESET Fields">
								</div>
								{{form.non_field_errors}}
						</div>

				</div>
		</form>
		</div>
</div>
{% endblock %}

paperauthor/templates/paperauthor/finalsubmit.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-x">
  <div class="container">
    {{paper}}
    <p>Please submit the final draft of the research paper complete with header as specified here in docx format. This paper will be published on the web portal.</p>
    <form method="post" enctype='multipart/form-data'>
      {% csrf_token %}
      {{form|crispy}}
      <input type="submit" class="btn btn-primary" value="Upload the Paper">
    </form>
  </div>
</div>
{% endblock %}

paperauthor/templates/paperauthor/finalsubmitsuccess.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}

<div class="content-x">
  <div class="container">
    {{paper}}
    <p>Submission Successful. Your paper will be published soon on the web portal.</p>
  </div>
</div>
{% endblock %}

paperauthor/templates/paperauthor/portal.html
 {% extends 'base.html' %}
{% load static %}
{% block title %} Author Portal | NMAMIT Annual Research Journal  {% endblock %}
{% block content %}
<div class="content-x">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h3>Username is : <b><i>{{user}}</i></b><br> You can submit the new manuscipts from this web portal</h3>
                <hr>
            </div>
            <div class="col-sm-12">
                <a href="{% url 'paperauthor:addpaper' %}" class="add-paper-x btn btn-warning"><img src="{% static 'images/edit.png' %}" class="margin-right-x">Add Paper</a>

                <table class="blue-grey lighten-4 table table-striped">
                    <thead>
                        <tr>
                            <th>Sl.</th>
                            <th>Paper Title</th>
                            <th>Status</th>
                            <th width="30">Details</th>
                            <th width="40">Track</th>
                        </tr>
                    </thead>
                    <tbody>
                      {% for el in papers %}
                        <tr>
                            <td>1</td>
                            <td>{{el.title}}</td>
                            <td>{{el.review_status}}</td>
                            <td><a href="{% url 'paperauthor:showpaper' paperslug=el.slug %}" class="btn btn-primary">Details</a></td>
                            <td><a href="{% url 'baseportal:track' %}?id={{el.track_id}}" class="btn btn-success">Track</a></td>
                        </tr>
                        	{% endfor %}

                    </tbody>
                </table>
            </div>
        </div>
    </div>
</div>
{% endblock %}

paperauthor/templates/paperauthor/resubmit.html
{% extends 'base.html' %}
{% load static %}
{% load widget_tweaks %}
{% load crispy_forms_tags %}
{% block title %}Resubmit Manuscript | NMAMIT Annual Research Journal  {% endblock %}

{% block content %}

<div class="content-x">
		<div class="container">
	<form method="post" enctype='multipart/form-data'>
		{% csrf_token %}
		{{ form.0|crispy }}
		{{ form.1|crispy }}
	    <button type="submit">Submit</button>
	</form>
</div>
</div>
{% endblock %}

paperauthor/templates/paperauthor/showpaper.html
{% extends 'base.html' %}
{% load static %}
{% block path %} HOME &gt; VIEW PAPER {%endblock %}
{% block title %} {{paper}} | NMAMIT Annual Research Journal  {% endblock %}
{% block content %}
<!-- START - CONTENT -->
<div class="content-x" style="height: 50%;">
    <div class="container">
        <div class="row">
            <div class="col-sm-12">
                <h1>Name of the Manuscript <b> {{paper}}</b></h1>
                <hr>
            </div>
            <div class="col-sm-8">
                <input type="text" id="trackIdText" class="trackIdCopy" value="{{paper.track_id}}">
            </div>
            <div class="col-sm-2">
                <button id="trackIdCopy" onclick="copyToClipboard()" class="btn btn-primary">Copy</button>
            </div>
            {% if paper.reviewer is None %}
            <div class="col-sm-12">
                <h4>Status: </h4><p>No Reviewer Assigned</p>
            </div>
            {% elif paper.review_complete is False %}
            <div class="col-sm-12">
                <h4>Status: </h4><p>Review in Process</p>
            </div>
            {% else %}
            <div class="col-sm-12">
                <h4>Status: </h4></h4><p>{{paper.review_status}}</p>
            </div>
            <div class="col-sm-8">
                <h3>Comments to Author</h3>
                <p>{{paper.paperreview.final_comments_to_author}}</p>
            </div>
            <div class="col-sm-12">
              <a class="btn btn-info" href="{% url 'paperauthor:annotate' %}?file={% url 'paperauthor:downloadpaper' paperslug=paper.slug %}">Open in E-Document</a>
                <a class="btn btn-info" href="{% url 'paperauthor:downloadpaper' paperslug=paper.slug %}">Download</a>

            </div>
            {% endif %}
            {% if paper.is_resubmission %}
            <div class="col-sm-12">
              <a class="btn btn-info" href="{% url 'paperauthor:downloadsuggestedcorrections' paperslug=paper.slug %}">
                Suggested Correction
              </a>
              <a class="btn btn-info" href="{% url 'paperauthor:downloadperformedcorrections' paperslug=paper.slug %}">
                Performed Correction
              </a>
            </div>
            {% endif %}
            {% if paper.is_resubmittable %}
              <a class="btn btn-info" href="{% url 'paperauthor:resubmitpaper' paperslug=paper.slug %}">Resubmit</a>
            {% endif %}
            {% if paper.is_finalsubmittable %}
              <a class="btn btn-info btn-red" href="{% url 'paperauthor:finalsubmitpaper' paperslug=paper.slug %}">Complete the Submission of the paper</a>
            {% endif %}
        </div>
    </div>
</div>
<script>
    function copyToClipboard() {
      document.getElementById("trackIdText").select();
      document.execCommand("Copy");
      alert("Copied");
    }
</script>

{% endblock %}